import '../../fastlane/Fastfile'

default_platform(:ios)

PROJECT = "EasUpdatesExampleBare"

XCODE_PROJECT = "#{PROJECT}.xcodeproj"
XCODE_WORKSPACE = "#{PROJECT}.xcworkspace"

XCODE_SCHEME = PROJECT
XCODE_SCHEME_DEV = "EasUpdatesExampleBareDev"
XCODE_SCHEME_QA = "EasUpdatesExampleBareQA"
XCODE_SCHEME_RELEASE = "EasUpdatesExampleBareRelease"

BUILD_DIR = "build"


platform :ios do

  before_all do |lane, options|
    setup_ci

    api_key = app_store_connect_api_key(
      is_key_content_base64: true
    )

    match(
      type: "appstore", 
      api_key: api_key,
      readonly: is_ci,
    )

  end


  lane :compile do |options|
    # compile the code
    track = options[:track]

    if (track.nil?) then
      UI.user_error!('The track is required. Either dev, qa or release')
    end


    scheme_to_use = case track
    when :dev
      XCODE_SCHEME_DEV
    when :qa
      XCODE_SCHEME_QA
    when :store
      XCODE_SCHEME_RELEASE
    else
      XCODE_SCHEME
    end

    build_ios_app(
      scheme: scheme_to_use,
      workspace: XCODE_WORKSPACE,
      export_method: "app-store",
      silent: true,
      clean: true,
      output_directory: "#{BUILD_DIR}/#{track}"
    )

  end

  private_lane :get_and_write_versions do |options|
    track = options[:track]
    # get latest version and build numbers
    get_versions
    # Set the runtime version in the Expo.plist file
    write_expo_plist(track: track)
    # write versions in the version.ts file
    write_version_ts
  end

  lane :dev do |options|
    track = :dev
    get_and_write_versions(track: track)
    compile(track: track)
  end
  
  lane :qa do |options|
    track = :qa
    get_and_write_versions(track: track)
    compile(track: track)
  end

  lane :store do |options|
    track = :store
    get_and_write_versions(track: track)
    compile(track: track)
  end

    # error block is executed when a error occurs
    error do |lane, exception|
      UI.error(exception.to_s)

      # Notify slack?
    end

 end
