fastlane_require 'dotenv'
import '../../fastlane/Fastfile'

default_platform(:android)

platform :android do
  
  lane :compile do |options|
    # compile the code
    track = options[:track]

    if (track.nil?) then
      UI.user_error!('The track is required. Either dev, qa or release')
    end

    gradle(task: 'clean')

    gradle(
      task: 'assemble',
      flavor: track.to_s,
      build_type: 'Release',
    )
  end

  private_lane :get_and_write_versions do |options|
    track = options[:track]
    # get latest version and build numbers
    get_versions
    # Set the runtime version in the Expo.plist file
    write_android_manifest(track: track)
    # write versions in the version.ts file
    write_version_ts
  end


  lane :dev do |options|
    track = :dev
    get_and_write_versions(track: track)
    compile(track: track)
  end
  
  lane :qa do |options|
    track = :qa
    get_and_write_versions(track: track)
    compile(track: track)
  end

  lane :store do |options|
    track = :store
    get_and_write_versions(track: track)
    compile(track: track)
  end


  # error block is executed when a error occurs
  error do |lane, exception|
    UI.error(exception.to_s)
  end
end